[package]
name = "landau-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argmin = "0.5.0" # Crate containing tools like scipy.optimize.fmin
